import java.util.*;
/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'admin' at '8/10/16 10:43 PM' with Gradle 2.9
 *
 * @author admin, @date 8/10/16 10:43 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
	
	
	public void  test() {
    
	List list = new ArrayList<String>();
	String input = null;
	String input1 = null;
	input1.length();
	
	
	
	
}

	
}


